/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator2;

/**
 *
 * @author chinmay-kulkarni-ubuntu
 */
public class CalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorFrame
     */
    int  NumEnter1;
    int  NumEnter2;
    String op;
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextArea();
        DIgitAdd = new javax.swing.JButton();
        Digit7 = new javax.swing.JButton();
        Digit8 = new javax.swing.JButton();
        Digit9 = new javax.swing.JButton();
        DigitSub = new javax.swing.JButton();
        Digit4 = new javax.swing.JButton();
        Digit5 = new javax.swing.JButton();
        Digit6 = new javax.swing.JButton();
        Digit2 = new javax.swing.JButton();
        Digit3 = new javax.swing.JButton();
        DigitMulti = new javax.swing.JButton();
        Digit1 = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        DigitZero = new javax.swing.JButton();
        DigitDot = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        DigitClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Result.setColumns(20);
        Result.setRows(5);
        Result.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(Result);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 50));

        DIgitAdd.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        DIgitAdd.setText("+");
        DIgitAdd.setBorder(new javax.swing.border.MatteBorder(null));
        DIgitAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DIgitAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DIgitAddMouseEntered(evt);
            }
        });
        DIgitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIgitAddActionPerformed(evt);
            }
        });
        getContentPane().add(DIgitAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 70, 50));
        DIgitAdd.getAccessibleContext().setAccessibleName("");
        DIgitAdd.getAccessibleContext().setAccessibleDescription("");

        Digit7.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit7.setText("7");
        Digit7.setBorder(new javax.swing.border.MatteBorder(null));
        Digit7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit7ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 74));
        Digit7.getAccessibleContext().setAccessibleName("");
        Digit7.getAccessibleContext().setAccessibleDescription("");

        Digit8.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit8.setText("8");
        Digit8.setBorder(new javax.swing.border.MatteBorder(null));
        Digit8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit8ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, 74));
        Digit8.getAccessibleContext().setAccessibleName("");
        Digit8.getAccessibleContext().setAccessibleDescription("");

        Digit9.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit9.setText("9");
        Digit9.setBorder(new javax.swing.border.MatteBorder(null));
        Digit9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit9ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 70, 74));
        Digit9.getAccessibleContext().setAccessibleName("");
        Digit9.getAccessibleContext().setAccessibleDescription("");

        DigitSub.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        DigitSub.setText("-");
        DigitSub.setBorder(new javax.swing.border.MatteBorder(null));
        DigitSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DigitSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitSubActionPerformed(evt);
            }
        });
        getContentPane().add(DigitSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 70, 50));
        DigitSub.getAccessibleContext().setAccessibleName("");
        DigitSub.getAccessibleContext().setAccessibleDescription("");

        Digit4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit4.setText("4");
        Digit4.setBorder(new javax.swing.border.MatteBorder(null));
        Digit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit4ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 74));
        Digit4.getAccessibleContext().setAccessibleName("");
        Digit4.getAccessibleContext().setAccessibleDescription("");

        Digit5.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit5.setText("5");
        Digit5.setBorder(new javax.swing.border.MatteBorder(null));
        Digit5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit5ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, 74));
        Digit5.getAccessibleContext().setAccessibleName("");
        Digit5.getAccessibleContext().setAccessibleDescription("");

        Digit6.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit6.setText("6");
        Digit6.setBorder(new javax.swing.border.MatteBorder(null));
        Digit6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit6ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 70, 74));
        Digit6.getAccessibleContext().setAccessibleName("");
        Digit6.getAccessibleContext().setAccessibleDescription("");

        Digit2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit2.setText("2");
        Digit2.setBorder(new javax.swing.border.MatteBorder(null));
        Digit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit2ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 70, 73));
        Digit2.getAccessibleContext().setAccessibleName("");
        Digit2.getAccessibleContext().setAccessibleDescription("");

        Digit3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit3.setText("3");
        Digit3.setBorder(new javax.swing.border.MatteBorder(null));
        Digit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit3ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, 74));
        Digit3.getAccessibleContext().setAccessibleName("");
        Digit3.getAccessibleContext().setAccessibleDescription("");

        DigitMulti.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        DigitMulti.setText("*");
        DigitMulti.setBorder(new javax.swing.border.MatteBorder(null));
        DigitMulti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DigitMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitMultiActionPerformed(evt);
            }
        });
        getContentPane().add(DigitMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, 50));
        DigitMulti.getAccessibleContext().setAccessibleName("");
        DigitMulti.getAccessibleContext().setAccessibleDescription("");

        Digit1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        Digit1.setText("1");
        Digit1.setBorder(new javax.swing.border.MatteBorder(null));
        Digit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Digit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digit1ActionPerformed(evt);
            }
        });
        getContentPane().add(Digit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, 74));
        Digit1.getAccessibleContext().setAccessibleName("");
        Digit1.getAccessibleContext().setAccessibleDescription("");

        btnEqual.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        btnEqual.setText("=");
        btnEqual.setBorder(new javax.swing.border.MatteBorder(null));
        btnEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(btnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 70, 50));
        btnEqual.getAccessibleContext().setAccessibleName("");
        btnEqual.getAccessibleContext().setAccessibleDescription("");

        DigitZero.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        DigitZero.setText("0");
        DigitZero.setBorder(new javax.swing.border.MatteBorder(null));
        DigitZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DigitZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitZeroActionPerformed(evt);
            }
        });
        getContentPane().add(DigitZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 70, 70));
        DigitZero.getAccessibleContext().setAccessibleName("");
        DigitZero.getAccessibleContext().setAccessibleDescription("");

        DigitDot.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        DigitDot.setText(".");
        DigitDot.setBorder(new javax.swing.border.MatteBorder(null));
        DigitDot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DigitDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitDotActionPerformed(evt);
            }
        });
        getContentPane().add(DigitDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 70, 70));
        DigitDot.getAccessibleContext().setAccessibleName("");
        DigitDot.getAccessibleContext().setAccessibleDescription("");

        btnDivision.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        btnDivision.setText("/");
        btnDivision.setBorder(new javax.swing.border.MatteBorder(null));
        btnDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 70, 70));
        btnDivision.getAccessibleContext().setAccessibleName("");
        btnDivision.getAccessibleContext().setAccessibleDescription("");

        DigitClear.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        DigitClear.setText("C");
        DigitClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitClearActionPerformed(evt);
            }
        });
        getContentPane().add(DigitClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumbers(String s) {
    String Nums = Result.getText() + s;
    Result.setText(Nums);
}

    private void Digit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit9ActionPerformed
EnterNumbers("9");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit9ActionPerformed

    private void DIgitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIgitAddActionPerformed
 NumEnter1=Integer.valueOf(Result.getText());
    Result.setText("");
      op="+";          
      // TODO add your handling code here:
    }//GEN-LAST:event_DIgitAddActionPerformed

    private void DigitSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitSubActionPerformed
 NumEnter1=Integer.valueOf(Result.getText());
      Result.setText("");
      op="-";        // TODO add your handling code here:
    }//GEN-LAST:event_DigitSubActionPerformed

    private void Digit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit6ActionPerformed
EnterNumbers("6");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit6ActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
                                            
    // First check if the result is not empty
    if (Result.getText().isEmpty()) {
        return; // Exit if there's nothing to calculate
    }

    // Parse the second number
    NumEnter2 = Integer.valueOf(Result.getText());

    // Variable to store the result of the calculation
    int calculationResult = 0;

    // Perform the calculation based on the operator
    switch (op) {
        case "+":
            calculationResult = NumEnter1 + NumEnter2;
            break;
        case "-":
            calculationResult = NumEnter1 - NumEnter2;
            break;
        case "*":
            calculationResult = NumEnter1 * NumEnter2;
            break;
        case "/":
            if (NumEnter2 != 0) {
                calculationResult = NumEnter1 / NumEnter2;
            } else {
                Result.setText("Error: Div by 0");
                return; // Exit if division by zero
            }
            break;
        default:
            return; // Exit if no valid operator
    }

    // Update the result JTextArea with the calculation result
    Result.setText(String.valueOf(calculationResult));
    // Reset operator to null after performing the calculation
    op = null;



         
    }//GEN-LAST:event_btnEqualActionPerformed

    private void DigitZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitZeroActionPerformed
EnterNumbers("0");   // TODO add your handling code here:
    }//GEN-LAST:event_DigitZeroActionPerformed

    private void Digit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit5ActionPerformed
EnterNumbers("5");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit5ActionPerformed

    private void Digit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit2ActionPerformed
EnterNumbers("2");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit2ActionPerformed

    private void DigitDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitDotActionPerformed
        // TODO add your handling code here:
        if(!Result.getText().contains(".") ){
            Result.setText(Result.getText()+ DigitDot.getText());
        }
    }//GEN-LAST:event_DigitDotActionPerformed

    private void Digit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_Digit8ActionPerformed

    private void Digit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit3ActionPerformed
EnterNumbers("3");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit3ActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        NumEnter1=Integer.valueOf(
                Result.getText());
      Result.setText("");
      op="/";
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void DigitClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitClearActionPerformed

                                               
    // Clear the result display
    Result.setText("");
    // Reset numbers and operator
    NumEnter1 = 0;
    NumEnter2 = 0;
    op = ""; // Clear operator


    }//GEN-LAST:event_DigitClearActionPerformed

    private void Digit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit7ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("7");
    }//GEN-LAST:event_Digit7ActionPerformed

    private void Digit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit4ActionPerformed
        EnterNumbers("4");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit4ActionPerformed

    private void Digit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digit1ActionPerformed
        EnterNumbers("1");        // TODO add your handling code here:
    }//GEN-LAST:event_Digit1ActionPerformed

    private void DigitMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitMultiActionPerformed
        NumEnter1=Integer.valueOf
        (Result.getText());
       Result.setText("");
        op="*";        // TODO add your handling code here:
    }//GEN-LAST:event_DigitMultiActionPerformed

    private void DIgitAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIgitAddMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DIgitAddMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIgitAdd;
    private javax.swing.JButton Digit1;
    private javax.swing.JButton Digit2;
    private javax.swing.JButton Digit3;
    private javax.swing.JButton Digit4;
    private javax.swing.JButton Digit5;
    private javax.swing.JButton Digit6;
    private javax.swing.JButton Digit7;
    private javax.swing.JButton Digit8;
    private javax.swing.JButton Digit9;
    private javax.swing.JButton DigitClear;
    private javax.swing.JButton DigitDot;
    private javax.swing.JButton DigitMulti;
    private javax.swing.JButton DigitSub;
    private javax.swing.JButton DigitZero;
    private javax.swing.JTextArea Result;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEqual;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
